name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.2
        with:
          aqua_version: v2.37.2
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.2
        with:
          aqua_version: v2.37.2
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
