name: Claude Renovate Review

permissions: {}

on:
  pull_request:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  claude-renovate-review:
    if: github.event.pull_request.user.login == 'renovate[bot]'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: koki-develop/claude-renovate-review@cda94ca660ec4eb22dc7808745e6e511b98b6ebc # v1.0.7
        with:
          claude-code-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          allowed-tools: |
            WebFetch(domain:github.com)
            WebFetch(domain:raw.githubusercontent.com)
            WebFetch(domain:www.npmjs.com)
