name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 15 * * *"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Deploy
        env:
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          bunx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          bunx vercel build --prod --token=$VERCEL_TOKEN
          bunx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
