name: Deploy Preview

permissions: {}

defaults:
  run:
    shell: bash

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup

      - name: Deploy
        id: deploy
        env:
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          bunx vercel pull --yes --environment=preview --token="${VERCEL_TOKEN}"
          bunx vercel build --token="${VERCEL_TOKEN}"
          PREVIEW_URL=$(bunx vercel deploy --prebuilt --token="${VERCEL_TOKEN}")
          echo "url=${PREVIEW_URL}" >> "$GITHUB_OUTPUT"

      - uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Deployed to Preview Environment

      - uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## :rocket: Deployed to Preview Environment :rocket:

            - ${{ steps.deploy.outputs.url }} (${{ github.event.pull_request.head.sha }})
