name: release

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 15 * * *" # 毎日 0 時

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Create .env
        run: |
          echo 'NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ vars.GA_MEASUREMENT_ID }}' >> .env

      - name: Deploy
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          yarn run vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          yarn run vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          yarn run vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
